# Generated by Django 5.2 on 2025-12-01 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovieAdmin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addmovie',
            name='discription',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='muser',
            name='password',
            field=models.CharField(max_length=100),
        ),
    ]
