# Generated by Django 5.2 on 2025-12-03 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovieAdmin', '0002_alter_addmovie_discription_alter_muser_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='addmovie',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='MovieAdmin.muser'),
            preserve_default=False,
        ),
    ]
