# Generated by Django 5.2 on 2025-11-10 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theatreApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theatre',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theatreApp.tuser'),
        ),
    ]
