# Generated by Django 5.2 on 2026-01-02 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MoviesApp', '0003_seatlock'),
    ]

    operations = [

        migrations.RunSQL(
            """
            ALTER TABLE MoviesApp_booking
            MODIFY seats LONGTEXT;
            """
        ),
    ]
